name: Python Package

on:
  push:
    branches:
      - main  # Or the name of the main branch you use
    tags:
      - 'v*'  # Tagging version, for example: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install tools for packaging and uploading

    - name: Build and upload package to PyPI
      run: |
        python setup.py sdist bdist_wheel  # Build the package
        twine upload dist/*  # Upload the package to PyPI using twine
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Set your PyPI username
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Set your PyPI password
